language: rust
rust:
- 1.32.0
- 1.33.0
- 1.34.0
- 1.35.0
- 1.36.0
- 1.37.0
- stable
- beta
- nightly
script:
- cargo build --verbose --no-default-features
- cargo test --verbose --no-default-features
- cargo build --verbose
- cargo test --verbose
- cargo build --verbose --all-features
- cargo test --verbose --all-features
env:
  global:
  - RUSTFLAGS="-C link-dead-code"
  - secure: k+5s8j7arJSoqS/7BnX7vBEXb1csFsn/cr+WCxRQtlV7bK8JkQ/3t3E1MCUpCSHJLb6K+GlRSkN6tWkhPVUpYA57J7+bSADJ2cAWBq2ArMubXMkMl/t7ibuOArGggDRLulYZ83kDZEkVcMs3QyAv7cGvSMnj6VehTeUrZsIreHmNGJnpsxuXqsfaHhiToWkO/KTRGHOuro7xQczCKzV54g7NAfIgWvcy3T5zVpkaNZWGd/BaRvkBRP8fZpqNBQSlG3Unq3q6wWIeLIJd3QWAQCrzDDMNIbiwsU/KHOJfVvvDFDJF/rzn1EwVvkWRQmT+GtPmLDCRV5OD4hmjVyEtdFU1aLaxxeQBNdSUb3SsDbnUkfyX+WgHEAYRxRAOGW8vhA7+9gaMI2fStkc5JwAcfrZxKkDd9YsUX4iYNk207zsRz/5M6gTWCw2e7jLj9kUGMiTy+008TRxAjSNbN9sl+FRMH5BPMDlgDM4Ohp1+JRq0Mfu1qT6hoYXb+AoRvHijw9HoqtaU2lTamuSN6+LFNJ0CDt2Qhy4jn+Dmp5ZlivcUVzpQpdZoPG00BnLK6YfYoCF9gFX194TM2T6ljhYGaL7ITZI9Cz4qMxD3r459aGz8sUAcTkSbTRMGpTb4fJVfvCgsP2IDfKO7WS/W4SbCzYMh7PfpQg03BAvld0y69O8=
  - secure: sF8l0788UwTlEjw+ctKwiw+73zLErGuah6Oh/zYjogwms27HDR7JxrWVXc/dvogwP0nuKoj5m8g4sbtIRkQDZ80OjEr1kefoE71fNDskDYXe4+lTP/RVHF4myTjVZ0HbrHLhiNzpP7NzzCURuOsXa6RGN7A6tSnpX5MZ7euW1HxF9Vjjebsrpko86AJbDESaJaBrFf40P+BJ0xKEEaygtAtnoYMEmSXzAAmOb6SAyDRx8do7433P6At2AEOTuUAocl/nefb36X4aEVfPPd23PVR1wICZmn1LwYccXbGZmW7OvhgU82P9Lb4SgsQtcDJdzOsH0yjsTimf/EDESLQhcD35MDGMUvL0nZ/sOWuTigZw8ax1CLna2kbxYwhZ3lfA8hqt9dkjzi6lwRRSP1CZD0YmaBA0S6H9zcmBdv551wn4nCGu4+uCYcvhqHh6cSZZGTSgiCZ3zr59TeMvAV5Fy3up4IhSYwrQYuPeZ3Wzzm3UEvGaTfmcgIEyqxRfBobNxzQI0I5PcvfXleHxuuOlZiMDFNQEO/dw5pbMaUdABggc0AR6Ph8dmScX3iCfuhzlErUFwNWGEifoojNquuj3+4FOkoAJ3hwqw+hdK3DS7cI2EFjTO9f6bBD72bbeo8lIylrbJo5KDAeIPzs0q1PX2s4DlSoRV39LggSaeZt/xAA=
after_success: |
  sudo apt-get update && sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev cmake gcc binutils-dev libiberty-dev &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make &&
  sudo make install && cd ../.. &&
  for file in target/debug/prettytable-*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&
  bash <(curl -s https://codecov.io/bash)
  rm -Rf master.tar.gz kcov-master
  git clone https://gist.github.com/deaf3815d2eecce72279.git ./publish_doc &&
  sh ./publish_doc/publish_doc.sh prettytable yes
